Upgrade to mongoid 9
mongoid/mongoid-locker pull request #105
Opened 2024-05-05 20:49 UTC by SairamSrinivasan

PR to upgrade monogid to v9 as it was just released: https://www.mongodb.com/docs/mongoid/master/release-notes/mongoid-9.0/

2024-05-05 20:50 UTC, SairamSrinivasan commented
I ran rspec and all the tests pass.

2024-05-05 21:13 UTC, dblock requested changes
Glad it works out of the box! Add to CI, https://github.com/mongoid/mongoid-locker/blob/master/.github/workflows/test.yml#L28, and CHANGELOG please?

2024-05-06 02:04 UTC, SairamSrinivasan commented
@dblock Thanks for the review. Can we release this as v3.0.0, bumping the version to a MAJOR?

2024-05-06 12:17 UTC, dblock requested changes
This is not a breaking change, so not 3.0, but let's bump version to 2.1.0 as part of this PR since it's a new feature.

2024-05-06 12:17 UTC, dblock commented on CHANGELOG.md
> +* [#105](https://github.com/mongoid/mongoid-locker/pull/105): Upgraded supported mongoid version to version 9.0 - [@saisrinivasan](https://github.com/SairamSrinivasan)
Change to "Added support for Mongoid 9.0". Don't forget the period at the end or danger will complain.

2024-05-07 07:21 UTC, dblock commented
Looks good, thank you. Will cut a release soon-ish unless someone beats me to it. Btw, lots of other mongoid- gems in this org could use similar help!

2024-05-07 07:21 UTC, merged

2024-05-07 08:58 UTC, dblock commented
I released 2.1.0.